### PR TITLE
#86 Add github url support

### PR DESCRIPTION
**Pull request by kotyara85**
Closes: #85 
Signed-off-by: kotyara85 <konrasko@gmail.com>

### CODE REVIEW

**Comment by mrrobot47** [comment]
@kotyara85 Thanks for the quick update, I was about to comment about `GITHUB_SERVER_URL`.

**Comment by mrrobot47** [comment]
@kotyara85 are the [Author URL's](https://github.com/rtCamp/action-slack-notify/blob/a5d50afba9ad399f8029256c690f296e8d8f363f/main.go#L203-L204) same as github.com users or they are different in enterprise hosted GitHub?

**Comment by kotyara85** [comment]
@mrrobot47 yeah, let me fix that

**Comment by kotyara85** [comment]
@mrrobot47 updated pr

**Comment by kotyara85** [comment]
@mrrobot47 When can we expected to this get merged?

**Pull request merged**
