### PR TITLE
Add automatic status to color mapping

### PR DESCRIPTION
**Pull request by lukasz-mitka**

### CODE REVIEW

**Comment by mrrobot47** [comment]
Hey @lukaszmitka-aptiv, thanks for the PR!
I will be taking a look at this and testing it later this week.

Till this PR is tested and approved, you can use something similar to this as well:
```yml
        SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"
```

**Comment by lukaszmitka-aptiv** [comment]
Hey @mrrobot47, thanks.
I'm using 
```
${{ job.status == 'success' && 'good' || job.status == 'cancelled' && '#808080' || 'danger' }}
```
but it's just horrible.

**Comment by mrrobot47** [comment]
I agree :smile: 
This is just till the time the PR is tested and approved.

**Comment by prioux** [comment]
Just want to say I like the PR's goal, but I think the documentation should still include an example where the color is explicitly specified. So maybe the sample YAML in the README.md could contain a comment:

```yaml
    SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
```

Also, maybe the README could document the new color mapping: `"success" => "good", "cancelled" => "#808080", "failure" => "danger"`. (There is a color called 'danger' btw?!)

**Comment by lukaszmitka-aptiv** [comment]
> Just want to say I like the PR's goal, but I think the documentation should still include an example where the color is explicitly specified. So maybe the sample YAML in the README.md could contain a comment:
> 
> ```yaml
>     SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
> ```
> 
> Also, maybe the README could document the new color mapping: `"success" => "good", "cancelled" => "#808080", "failure" => "danger"`. (There is a color called 'danger' btw?!)

While I agree, I don't have time right now to do it.
Maybe you or someone else would like to do it in separate PR and get this one merged?

**Comment by mrrobot47** [comment]
@lukaszmitka-aptiv I will update the readme. No need to worry about that.

**Review by JuriBurakov — APPROVED** [review]

**Comment by lukasz-mitka** [comment]
@mrrobot47 @JuriBurakov are you guys going to merge this anytime soon?

**Comment by dhsathiya** [comment]
Tested and LGTM :tada:

**Comment by mrrobot47** [comment]
@lukasz-mitka This has been released in https://github.com/rtCamp/action-slack-notify/releases/tag/v2.1.3.
Please use `uses: rtCamp/action-slack-notify@v2` (if you are not already using `@v2` tag) for the latest changes.

**Pull request merged**
