### PR TITLE
Feat/allow link names slack

### PR DESCRIPTION
**Pull request by bogaertg**
Goal : enable to mention user in slack

How: Add flag link_names for webhook request

### CODE REVIEW

**Comment by bogaertg** [comment]
@dhsathiya ?

**Comment by mrrobot47** [comment]
@bogaertg thanks for the PR, this will be tested in the coming week. LGTM, if it works as intended, this feature will be released in the coming week with credits to you in the release notes for the same.

**Comment by mrrobot47** [comment]
Thanks for the PR :pray:

**Comment by mrrobot47** [comment]
This has been released in https://github.com/rtCamp/action-slack-notify/releases/tag/v2.2.0
You can use `@v2` tag to use this feature.

**Pull request merged**
